### ISSUE TITLE
Daily notification not working

### ISSUE THREAD

**Issue by Jean1995** [MaxNoe/mensabot#1]
Daily notification did work on monday but doesnt work anymore

**Comment by maxnoe** [comment]
No idea why this happend today. The scheduler reported that it has missed the jobs by one minute. I improved the logging to get an idea if this happens again.

**Comment by maxnoe** [comment]
I allowed the scheduler to process jobs up to 15 Minutes after they were scheduled. This should fix this issue.  782c9c8a465d
