### ISSUE TITLE
/start@tudoMensaBot funktioniert nicht

### ISSUE THREAD

**Issue by jheuel** [MaxNoe/mensabot#2]
Hallo Max,

in unserer Gruppe kommt trotz abonniertem Mensaplan nichts an. Der Rest funktioniert prima!

Gruß 
Johannes

**Comment by maxnoe** [comment]
das /start funktioniert, der job wurde hinzugefügt. In unregelmäßigen abständen versagt aber der scheduler. Noch keine Ahnung woran das liegt,

**Comment by maxnoe** [comment]
Sollte gefixt sein. Die Option für die Toleranz des Sendezeitpunkts war falsch.
